/**
 * Launcher long-press shortcuts. Icons are adaptive mipmaps generated by the
 * expo-quick-actions config plugin from assets/shortcut-*.png.
 */
import { useEffect } from 'react';
import { Platform } from 'react-native';
import * as QuickActions from 'expo-quick-actions';

import { routeTo, type RouteTarget } from './deepLinks';

const ITEMS: QuickActions.Action[] = [
  { id: 'search', title: 'Search deals', icon: 'shortcut_search' },
  { id: 'saved', title: 'Saved deals', icon: 'shortcut_saved' },
  { id: 'check', title: 'Check a price', icon: 'shortcut_checkprice' },
];

function targetFor(id: string): RouteTarget | null {
  if (id === 'search') return { kind: 'search' };
  if (id === 'saved') return { kind: 'saved' };
  if (id === 'check') return { kind: 'check' };
  return null;
}

export function useQuickActionRouting(): void {
  useEffect(() => {
    if (Platform.OS !== 'android') return;
    QuickActions.setItems(ITEMS).catch(() => {});
    if (QuickActions.initial) routeTo(targetFor(QuickActions.initial.id));
    const sub = QuickActions.addListener((action) => routeTo(targetFor(action.id)));
    return () => sub.remove();
  }, []);
}
